"""Auto-ABM standardized ABM kernel (Mesa wrapper, pure Python)."""

from __future__ import annotations

from abm_kernel.base import ABMAgent, ABMModel, KernelAgent, KernelModel
from abm_kernel.behavior import (
    MechanismSpec,
    ModelBehavior,
    get_behavior,
    register_behavior,
)
from abm_kernel.builder import build_model
from abm_kernel.comparison import (
    ComparisonPlan,
    HypothesisRun,
    expand_comparison,
    rank_hypotheses,
)
from abm_kernel.errors import (
    BuildError,
    ConfigError,
    KernelError,
    MechanismError,
    TraceError,
)
from abm_kernel.loader import load_behavior_from_file
from abm_kernel.mechanism_graph import build_mechanism_graph
from abm_kernel.phenomenon import evaluate_metric, evaluate_phenomenon, parse_target
from abm_kernel.runner import ExperimentRunner, RunError, expand, run_model, simulate
from abm_kernel.schemas import (
    AgentType,
    Artifact,
    Environment,
    ExperimentConfig,
    ExperimentDesign,
    GraphEdge,
    GraphNode,
    Initialization,
    Mechanism,
    MechanismComparisonStudy,
    MechanismGraph,
    MechanismGraphView,
    MechanismHypothesis,
    MetricFit,
    ModelConfig,
    Observer,
    Parameter,
    PhenomenonFit,
    PhenomenonMetric,
    ReproManifest,
    RunRecord,
    SearchNode,
    SearchTree,
    SpaceKind,
    SpaceSnapshot,
    StateVariable,
    SweepAxis,
    TargetPhenomenon,
    VizDataRef,
    VizEncoding,
    VizSpec,
    load_model_config,
    missing_fields,
    parse_experiment_config,
    parse_model_config,
    parse_search_tree,
    parse_study,
    parse_target_phenomenon,
    parse_viz_spec,
)
from abm_kernel.schemas.run_plan import RunPlan
from abm_kernel.search_tree import (
    SearchCandidate,
    build_search_tree,
    build_study_search_tree,
    prune_below,
)
from abm_kernel.space import build_space_snapshot
from abm_kernel.trace import TraceWriter
from abm_kernel.validate import validate_mechanisms_source
from abm_kernel.version import KERNEL_VERSION

__version__ = KERNEL_VERSION

__all__ = [
    "KERNEL_VERSION",
    "ABMAgent",
    "ABMModel",
    "AgentType",
    "Artifact",
    "BuildError",
    "ComparisonPlan",
    "ConfigError",
    "Environment",
    "ExperimentConfig",
    "ExperimentDesign",
    "ExperimentRunner",
    "GraphEdge",
    "GraphNode",
    "HypothesisRun",
    "Initialization",
    "KernelAgent",
    "KernelError",
    "KernelModel",
    "Mechanism",
    "MechanismComparisonStudy",
    "MechanismError",
    "MechanismGraph",
    "MechanismGraphView",
    "MechanismHypothesis",
    "MechanismSpec",
    "MetricFit",
    "ModelBehavior",
    "ModelConfig",
    "Observer",
    "Parameter",
    "PhenomenonFit",
    "PhenomenonMetric",
    "ReproManifest",
    "RunError",
    "RunPlan",
    "RunRecord",
    "SearchCandidate",
    "SearchNode",
    "SearchTree",
    "SpaceKind",
    "SpaceSnapshot",
    "StateVariable",
    "SweepAxis",
    "TargetPhenomenon",
    "TraceError",
    "TraceWriter",
    "VizDataRef",
    "VizEncoding",
    "VizSpec",
    "__version__",
    "build_mechanism_graph",
    "build_model",
    "build_search_tree",
    "build_space_snapshot",
    "build_study_search_tree",
    "evaluate_metric",
    "evaluate_phenomenon",
    "expand",
    "expand_comparison",
    "get_behavior",
    "load_behavior_from_file",
    "load_model_config",
    "missing_fields",
    "parse_experiment_config",
    "parse_model_config",
    "parse_search_tree",
    "parse_study",
    "parse_target_phenomenon",
    "parse_target",
    "parse_viz_spec",
    "prune_below",
    "rank_hypotheses",
    "register_behavior",
    "run_model",
    "simulate",
    "validate_mechanisms_source",
]
