import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import { lazySchema } from '../../utils/lazySchema.js'
import { buildAttribution, buildChangepoints } from '../../server/abm/attributionService.js'
import { ABM_ATTRIBUTE_TOOL_NAME } from './constants.js'
import { attributionEnvelope, serializeEnvelope } from './abmCardEnvelope.js'

const DESCRIPTION =
  'Decompose a metric change over a tick interval into per-mechanism contributions computed from the real trace.'

const PROMPT = `Quantitative mechanism attribution for a run's metric over [from, to].

The server decomposes the metric's actual change into signed per-mechanism
state-transition flows read from the real trace (gains = transitions into the
observed state, losses = transitions out). It also reports coverage (how much
of the change mechanisms explain) and the residual (changes no mechanism
caused, e.g. initialization). Nothing here is generated by a language model —
cite these numbers directly in explanations instead of guessing mechanism
importance. Call this BEFORE abm_explain_interval when the user asks "why did
X change": the contributions tell you which mechanism_ids to cite.

If from/to are omitted the whole run is attributed. When the response has
supported=false, say so honestly — do not invent contributions. The response
also includes detected changepoints (salient slope changes) you can use to
pick tighter intervals.`

const contributionSchema = () =>
  z.object({
    mechanism_id: z.string(),
    gains: z.number(),
    losses: z.number(),
    net: z.number(),
    agents: z.number(),
  })

const changepointSchema = () =>
  z.object({
    metric: z.string(),
    tick: z.number(),
    score: z.number(),
    beforeSlope: z.number(),
    afterSlope: z.number(),
    direction: z.enum(['accelerate', 'decelerate', 'reversal']),
  })

const inputSchema = lazySchema(() =>
  z.strictObject({
    runId: z.string().describe('The run to attribute'),
    metric: z.string().describe('The observer/metric id to decompose (e.g. "infected")'),
    from: z.number().optional().describe('Interval start tick (inclusive); default 0'),
    to: z.number().optional().describe('Interval end tick (inclusive); default = end of run'),
    note: z.string().optional().describe('Short user-facing note shown on the card'),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.object({
    runId: z.string(),
    metric: z.string(),
    from: z.number(),
    to: z.number(),
    supported: z.boolean(),
    reason: z.string().optional(),
    metricStart: z.number().nullable(),
    metricEnd: z.number().nullable(),
    actualDelta: z.number().nullable(),
    attributedNet: z.number(),
    residual: z.number().nullable(),
    coverage: z.number().nullable(),
    contributions: z.array(contributionSchema()),
    changepoints: z.array(changepointSchema()),
    note: z.string().optional(),
    error: z.string().optional(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>

export type Output = z.infer<OutputSchema>

export const AttributeIntervalTool = buildTool({
  name: ABM_ATTRIBUTE_TOOL_NAME,
  searchHint: 'attribute metric change per mechanism quantitative trace',
  maxResultSizeChars: 60_000,
  async description() {
    return DESCRIPTION
  },
  async prompt() {
    return PROMPT
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return 'Attribute Interval'
  },
  isReadOnly() {
    return true
  },
  isConcurrencySafe() {
    return true
  },
  toAutoClassifierInput(input) {
    return `${input.runId} ${input.metric} [${input.from ?? 0},${input.to ?? 'end'}]`
  },
  renderToolUseMessage() {
    return null
  },
  async call({ runId, metric, from, to, note }) {
    const lo = from ?? 0
    const hi = to ?? Number.POSITIVE_INFINITY
    const [attribution, changepoints] = await Promise.all([
      buildAttribution(runId, metric, lo, hi),
      buildChangepoints(runId, metric),
    ])
    if (!attribution) {
      const reason = `Run not found or has no trace: ${runId}`
      return {
        data: {
          runId,
          metric,
          from: lo,
          to: to ?? lo,
          supported: false,
          reason,
          metricStart: null,
          metricEnd: null,
          actualDelta: null,
          attributedNet: 0,
          residual: null,
          coverage: null,
          contributions: [],
          changepoints: [],
          error: reason,
        },
      }
    }
    const { mapping: _mapping, ...rest } = attribution
    return {
      data: {
        ...rest,
        changepoints: changepoints?.changepoints ?? [],
        ...(note ? { note } : {}),
      },
    }
  },
  mapToolResultToToolResultBlockParam(content, toolUseID) {
    const out = content as Output
    return {
      tool_use_id: toolUseID,
      type: 'tool_result',
      content: serializeEnvelope(
        attributionEnvelope({
          runId: out.runId,
          metric: out.metric,
          from: out.from,
          to: out.to,
          supported: out.supported,
          ...(out.reason !== undefined ? { reason: out.reason } : {}),
          actualDelta: out.actualDelta,
          attributedNet: out.attributedNet,
          residual: out.residual,
          coverage: out.coverage,
          contributions: out.contributions,
          ...(out.note !== undefined ? { note: out.note } : {}),
        }),
      ),
    }
  },
} satisfies ToolDef<InputSchema, OutputSchema>)
