import type { CreateSimulationBody } from './api/abmClient'

export type AbmCaseTemplate =
  | 'rumor'
  | 'sir'
  | 'schelling'
  | 'diffusion'
  | 'opinion'
  | 'public_goods'
  | 'social_influence'
  | 'wildfire'

/** High-level grouping for the case library (keeps the picker organized). */
export type AbmCaseCategory =
  | '空间自组织'
  | '网络传播与扩散'
  | '意见与极化'
  | '合作与制度'
  | '阈值与集体行动'

/** Category display order in the case library. */
export const ABM_CASE_CATEGORIES: AbmCaseCategory[] = [
  '空间自组织',
  '网络传播与扩散',
  '意见与极化',
  '合作与制度',
  '阈值与集体行动',
]

export interface AbmCaseStudy {
  id: string
  name: string
  subtitle: string
  category: AbmCaseCategory
  domain: string
  template: AbmCaseTemplate
  canvas: '网格斑块' | '社会网络' | '移动个体' | '混合场景'
  scale: string
  difficulty: '入门' | '进阶' | '研究级'
  tags: string[]
  summary: string
  mechanism: string
  metrics: string[]
  experiments: string[]
  defaults?: Pick<CreateSimulationBody, 'seed' | 'steps' | 'params'>
}

export interface AbmResearchAgent {
  id: string
  name: string
  role: string
  when: string
  checks: string[]
}

export interface AbmResearchSkill {
  id: string
  name: string
  field: string
  summary: string
  source?: string
  sourceUrl?: string
}

export interface AbmResearchMcpServer {
  id: string
  name: string
  category: string
  summary: string
  sourceUrl: string
}

export const ABM_CASE_LIBRARY: AbmCaseStudy[] = [
  {
    id: 'schelling-urban-segregation',
    name: 'Schelling 城市隔离',
    subtitle: '邻居偏好如何放大为空间隔离',
    category: '空间自组织',
    domain: '城市与迁居',
    template: 'schelling',
    canvas: '网格斑块',
    scale: '80 x 80 patches',
    difficulty: '入门',
    tags: ['经典模型', '空间涌现', '阈值'],
    summary: '用两类居民和空置格点展示微弱偏好如何累积成宏观隔离格局。',
    mechanism: '个体检查邻域同类比例，低于容忍阈值时迁往可接受位置。',
    metrics: ['segregation', 'unhappy', 'moves'],
    experiments: ['容忍阈值扫描', '空置率对比', '多随机种子稳健性'],
    defaults: { steps: 120, params: { tolerance: 0.35 } },
  },
  {
    id: 'wildfire-fuel-front',
    name: '山火燃料斑块蔓延',
    subtitle: '风向、燃料密度与飞火点的空间扩散',
    category: '空间自组织',
    domain: '灾害与环境',
    template: 'wildfire',
    canvas: '网格斑块',
    scale: '200 x 200 patches',
    difficulty: '进阶',
    tags: ['森林火灾', '空间扩散', '干预'],
    summary: '模拟火线沿可燃斑块推进、燃尽区形成以及风向造成的非对称蔓延。',
    mechanism: '燃料格点受邻近火点、风向权重和飞火概率共同影响而点燃。',
    metrics: ['burning', 'burned_rate', 'fuel'],
    experiments: ['燃料密度敏感性', '风向干预', '防火带反事实'],
    defaults: { steps: 180, params: { fuel_density: 0.68, ignition_probability: 0.34 } },
  },
  {
    id: 'rumor-platform-moderation',
    name: '平台谣言与辟谣干预',
    subtitle: '转发网络中的传播、遗忘与治理窗口',
    category: '网络传播与扩散',
    domain: '舆情与传播',
    template: 'rumor',
    canvas: '社会网络',
    scale: '2k nodes / sparse graph',
    difficulty: '进阶',
    tags: ['谣言', '干预', '网络传播'],
    summary: '把用户看作网络节点，比较早期辟谣、限流和延迟治理对传播峰值的影响。',
    mechanism: '感染式接触传播叠加康复/遗忘过程，干预参数改变传播概率或恢复率。',
    metrics: ['infected', 'recovered', 'susceptible'],
    experiments: ['干预时点对比', '传播概率扫描', '种子节点鲁棒性'],
    defaults: { steps: 160, params: { beta: 0.22, gamma: 0.08 } },
  },
  {
    id: 'opinion-polarization-confidence',
    name: '意见极化与有限信任',
    subtitle: '相近才互动如何导致共识或分裂',
    category: '意见与极化',
    domain: '意见动力学',
    template: 'opinion',
    canvas: '社会网络',
    scale: '120 agents',
    difficulty: '进阶',
    tags: ['极化', '意见连续值', '网络结构'],
    summary: '连续意见在有限信任阈值内相互靠近，阈值过窄会形成多峰极化。',
    mechanism: '个体只受意见距离小于阈值的邻居影响，并按学习率更新意见。',
    metrics: ['opinion_mean', 'opinion_variance', 'clusters'],
    experiments: ['信任阈值扫描', '网络密度对比', '桥接节点干预'],
    defaults: { steps: 140, params: { confidence: 0.28, mu: 0.32 } },
  },
  {
    id: 'public-goods-cooperation',
    name: '公共品合作涌现',
    subtitle: '收益放大、模仿与合作崩塌',
    category: '合作与制度',
    domain: '集体行动',
    template: 'public_goods',
    canvas: '社会网络',
    scale: '200 players',
    difficulty: '研究级',
    tags: ['博弈论', '合作', '制度'],
    summary: '玩家在局部网络中合作或背叛，收益差通过 Fermi 规则驱动策略模仿。',
    mechanism: '合作成本进入公共池并放大后分配，个体按收益差与噪声复制邻居策略。',
    metrics: ['cooperation_rate', 'mean_payoff'],
    experiments: ['惩罚阈值扫描', '网络结构对比', '制度冲击反事实'],
    defaults: { steps: 240, params: { multiplier: 1.8, selection_strength: 0.55 } },
  },
  {
    id: 'innovation-adoption-bass',
    name: '创新扩散与采纳曲线',
    subtitle: '外部宣传和邻居模仿共同形成 S 曲线',
    category: '网络传播与扩散',
    domain: '创新与市场',
    template: 'diffusion',
    canvas: '社会网络',
    scale: '1k adopters',
    difficulty: '入门',
    tags: ['扩散', '采纳', '市场'],
    summary: '同时建模广告触达和社会模仿，观察采纳曲线、峰值和饱和速度。',
    mechanism: '未采纳者受外部采纳概率和已采纳邻居比例共同影响。',
    metrics: ['adopted', 'adoption_rate'],
    experiments: ['外部影响扫描', 'KOL 播种', '网络密度对比'],
    defaults: { steps: 130, params: { external_influence: 0.015, imitation_rate: 0.18 } },
  },
  {
    id: 'threshold-cascade-mobilization',
    name: '阈值级联与集体动员',
    subtitle: '少数激活者如何触发网络级联',
    category: '阈值与集体行动',
    domain: '社会运动',
    template: 'social_influence',
    canvas: '社会网络',
    scale: '800 agents',
    difficulty: '研究级',
    tags: ['复杂传染', '阈值', '级联'],
    summary: '个体只有在活跃邻居比例超过自身阈值时才参与，用于解释动员临界点。',
    mechanism: '异质阈值叠加网络位置，初始种子可能触发或无法触发全局级联。',
    metrics: ['active', 'activation_rate', 'cascade_size'],
    experiments: ['种子位置反事实', '阈值分布扫描', '网络断边干预'],
    defaults: { steps: 100, params: { threshold_mean: 0.32 } },
  },
  {
    id: 'sir-campus-contact',
    name: '校园接触传播',
    subtitle: '班级、宿舍和活动造成的空间接触风险',
    category: '空间自组织',
    domain: '公共卫生',
    template: 'sir',
    canvas: '网格斑块',
    scale: '120 x 120 patches',
    difficulty: '进阶',
    tags: ['SIR', '空间接触', '政策'],
    summary: '在空间网格上模拟感染扩散、恢复和隔离策略，观察峰值与持续时间。',
    mechanism: '感染者在邻域内传播，康复者退出感染链，隔离降低局部传播概率。',
    metrics: ['infected', 'recovered', 'susceptible'],
    experiments: ['隔离强度扫描', '初始感染点对比', '时间窗口干预'],
    defaults: { steps: 180, params: { beta: 0.28, gamma: 0.06 } },
  },
  {
    id: 'housing-gentrification',
    name: '社区绅士化迁居',
    subtitle: '租金压力、邻里偏好与空间替换',
    category: '空间自组织',
    domain: '城市社会学',
    template: 'schelling',
    canvas: '网格斑块',
    scale: '100 x 100 patches',
    difficulty: '研究级',
    tags: ['迁居', '不平等', '空间结构'],
    summary: '用居民类型和迁居阈值近似社区替换过程，观察局部偏好如何形成片区化。',
    mechanism: '居民根据邻域组成和承受阈值迁移，宏观上出现替换带与空间分层。',
    metrics: ['segregation', 'unhappy', 'moves'],
    experiments: ['住房补贴反事实', '阈值异质性', '空置率扰动'],
    defaults: { steps: 160, params: { tolerance: 0.42 } },
  },
  {
    id: 'evacuation-information',
    name: '疏散信息扩散',
    subtitle: '风险认知、邻居提醒与路径拥堵',
    category: '阈值与集体行动',
    domain: '应急管理',
    template: 'social_influence',
    canvas: '混合场景',
    scale: '500 residents',
    difficulty: '研究级',
    tags: ['疏散', '风险传播', '干预'],
    summary: '把疏散意愿看作阈值激活过程，比较广播、邻居提醒和关键节点告警。',
    mechanism: '个体在风险提醒比例超过阈值后行动，行动规模受网络位置和初始告警影响。',
    metrics: ['active', 'activation_rate'],
    experiments: ['广播时序干预', '关键节点告警', '阈值分布不确定性'],
    defaults: { steps: 120, params: { threshold_mean: 0.26 } },
  },
  {
    id: 'market-herding',
    name: '市场羊群行为',
    subtitle: '局部模仿与外部信号造成非理性波动',
    category: '意见与极化',
    domain: '经济行为',
    template: 'opinion',
    canvas: '社会网络',
    scale: '300 traders',
    difficulty: '进阶',
    tags: ['市场', '从众', '连续意见'],
    summary: '把投资倾向作为连续意见，研究外部信号与邻居影响如何制造波动。',
    mechanism: '交易者在信任范围内受邻居观点吸引，同时受外部信号轻微拉动。',
    metrics: ['opinion_mean', 'opinion_variance'],
    experiments: ['信号强度扫描', '网络集中度对比', '冲击恢复实验'],
    defaults: { steps: 160, params: { confidence: 0.22, mu: 0.25 } },
  },
  {
    id: 'resource-commons-fishery',
    name: '公共渔场资源治理',
    subtitle: '合作捕捞、惩罚制度与收益稳定性',
    category: '合作与制度',
    domain: '资源治理',
    template: 'public_goods',
    canvas: '社会网络',
    scale: '160 households',
    difficulty: '研究级',
    tags: ['公共池资源', '制度', '稳健性'],
    summary: '用公共品博弈近似共同资源治理，比较惩罚阈值和收益放大对合作率的影响。',
    mechanism: '个体在收益差驱动下复制邻居策略，惩罚和制度规则改变合作收益结构。',
    metrics: ['cooperation_rate', 'mean_payoff'],
    experiments: ['制度强度扫描', '多种子合奏', '收益冲击反事实'],
    defaults: { steps: 260, params: { punishment_threshold: 0.25 } },
  },
  {
    id: 'migration-chain-network',
    name: '迁移链网络扩散',
    subtitle: '亲友网络如何降低迁移门槛',
    category: '网络传播与扩散',
    domain: '人口迁移',
    template: 'diffusion',
    canvas: '社会网络',
    scale: '1.5k households',
    difficulty: '进阶',
    tags: ['迁移', '网络外部性', '扩散'],
    summary: '把迁移决策看成采纳过程，已迁移亲友越多，迁移概率越高。',
    mechanism: '外部机会信号和邻居采纳比例共同提升未迁移者采纳概率。',
    metrics: ['adopted', 'adoption_rate'],
    experiments: ['机会信号扫描', '初始迁移者位置', '网络断裂反事实'],
    defaults: { steps: 150, params: { external_influence: 0.01, imitation_rate: 0.24 } },
  },
  {
    id: 'school-norm-diffusion',
    name: '校园规范扩散',
    subtitle: '同伴压力与规范采纳的临界点',
    category: '阈值与集体行动',
    domain: '教育社会学',
    template: 'social_influence',
    canvas: '社会网络',
    scale: '600 students',
    difficulty: '进阶',
    tags: ['规范', '同伴影响', '阈值'],
    summary: '学生在同伴采纳比例达到阈值后接受某种学习/行为规范。',
    mechanism: '个体阈值和社群结构共同决定规范是否跨社群扩散。',
    metrics: ['active', 'activation_rate'],
    experiments: ['班级桥接干预', '阈值异质性', '关键学生播种'],
    defaults: { steps: 100, params: { threshold_mean: 0.3 } },
  },
  {
    id: 'traffic-route-choice',
    name: '交通路线选择拥堵',
    subtitle: '经验学习和局部信息造成拥堵转移',
    category: '合作与制度',
    domain: '交通系统',
    template: 'public_goods',
    canvas: '混合场景',
    scale: '300 commuters',
    difficulty: '研究级',
    tags: ['交通', '选择', '反馈'],
    summary: '用策略选择近似通勤者路线调整，观察局部收益反馈如何造成拥堵迁移。',
    mechanism: '通勤者依据邻居/历史收益复制路线策略，整体拥堵表现为合作率和收益变化。',
    metrics: ['cooperation_rate', 'mean_payoff'],
    experiments: ['信息发布策略', '收费反事实', '网络分层干预'],
    defaults: { steps: 220, params: { selection_strength: 0.7 } },
  },
  {
    id: 'land-use-firebreak-policy',
    name: '土地利用与防火带政策',
    subtitle: '异质燃料景观中的政策边界效果',
    category: '空间自组织',
    domain: '生态治理',
    template: 'wildfire',
    canvas: '网格斑块',
    scale: '240 x 240 patches',
    difficulty: '研究级',
    tags: ['土地利用', '防火带', '空间政策'],
    summary: '用山火扩散模型评估不同燃料布局和防火带宽度对燃尽面积的影响。',
    mechanism: '燃料异质性改变火线连通性，防火带降低跨区域点燃概率。',
    metrics: ['burning', 'burned_rate', 'fuel'],
    experiments: ['防火带宽度扫描', '燃料斑块异质性', '风向反事实'],
    defaults: { steps: 220, params: { fuel_density: 0.72, spotting_probability: 0.04 } },
  },
  {
    id: 'forest-percolation-critical',
    name: '森林火灾渗流临界',
    subtitle: '燃料密度跨越临界点时的相变',
    category: '空间自组织',
    domain: '复杂系统',
    template: 'wildfire',
    canvas: '网格斑块',
    scale: '200 x 200 patches',
    difficulty: '研究级',
    tags: ['渗流', '相变', '临界现象'],
    summary: '经典 forest-fire 渗流：燃料密度略微变化就让火势从局部熄灭跳变为全局燃尽。',
    mechanism: '点燃沿连通燃料簇传播，密度越过渗流阈值时连通簇突然贯穿整片网格。',
    metrics: ['burned_rate', 'burning', 'fuel'],
    experiments: ['密度临界扫描', '有限尺度标度', '点火位置鲁棒性'],
    defaults: { steps: 160, params: { fuel_density: 0.59, ignition_probability: 1.0 } },
  },
  {
    id: 'vaccination-hesitancy-grid',
    name: '疫苗犹豫与群体免疫',
    subtitle: '空间接种缺口如何留下传播走廊',
    category: '空间自组织',
    domain: '公共卫生',
    template: 'sir',
    canvas: '网格斑块',
    scale: '150 x 150 patches',
    difficulty: '进阶',
    tags: ['疫苗', '群体免疫', '空间异质'],
    summary: '在空间网格上比较均匀接种与聚集性犹豫，观察免疫缺口如何维持局部暴发。',
    mechanism: '易感者按邻域感染压力被感染，接种者移出传播链；空间聚集的未接种者形成走廊。',
    metrics: ['infected', 'recovered', 'susceptible'],
    experiments: ['接种率扫描', '空间聚集度对比', '初始感染点鲁棒性'],
    defaults: { steps: 200, params: { beta: 0.3, gamma: 0.07 } },
  },
  {
    id: 'epidemic-superspreader-network',
    name: '超级传播者网络暴发',
    subtitle: '度分布不均如何放大早期传播',
    category: '网络传播与扩散',
    domain: '公共卫生',
    template: 'rumor',
    canvas: '社会网络',
    scale: '3k nodes / heavy-tailed',
    difficulty: '研究级',
    tags: ['超级传播者', '无标度', '接触网络'],
    summary: '在异质接触网络上研究少数高连接节点如何主导暴发峰值与到达时间。',
    mechanism: '接触传播叠加恢复过程，高度节点更早被感染并向大量邻居扩散。',
    metrics: ['infected', 'recovered', 'susceptible'],
    experiments: ['高度节点保护', '传播概率扫描', '早期干预时点'],
    defaults: { steps: 150, params: { beta: 0.18, gamma: 0.06 } },
  },
  {
    id: 'viral-marketing-launch',
    name: '病毒式营销上市',
    subtitle: '种子投放与口碑放大的组合策略',
    category: '网络传播与扩散',
    domain: '市场营销',
    template: 'diffusion',
    canvas: '社会网络',
    scale: '2k consumers',
    difficulty: '进阶',
    tags: ['口碑', '种子投放', '增长曲线'],
    summary: '比较广撒网广告与关键节点种子投放对采纳速度和最终渗透率的影响。',
    mechanism: '未采纳者受广告触达与已采纳邻居比例双重驱动，种子位置改变早期斜率。',
    metrics: ['adopted', 'adoption_rate'],
    experiments: ['种子预算分配', '外部影响扫描', '网络社群结构对比'],
    defaults: { steps: 120, params: { external_influence: 0.02, imitation_rate: 0.2 } },
  },
  {
    id: 'media-echo-chamber',
    name: '媒体回音室与极化',
    subtitle: '同质连接与有限信任的叠加放大',
    category: '意见与极化',
    domain: '传播政治',
    template: 'opinion',
    canvas: '社会网络',
    scale: '400 agents',
    difficulty: '研究级',
    tags: ['回音室', '极化', '同质性'],
    summary: '研究同质性网络与窄信任阈值如何共同锁死意见簇，形成难以弥合的回音室。',
    mechanism: '个体只与意见相近的邻居互动并更新，网络同质性削弱跨簇桥接。',
    metrics: ['opinion_variance', 'clusters', 'opinion_mean'],
    experiments: ['信任阈值扫描', '桥接节点注入', '同质性强度对比'],
    defaults: { steps: 160, params: { confidence: 0.18, mu: 0.3 } },
  },
  {
    id: 'climate-treaty-cooperation',
    name: '气候条约减排合作',
    subtitle: '收益放大、惩罚与搭便车张力',
    category: '合作与制度',
    domain: '全球治理',
    template: 'public_goods',
    canvas: '社会网络',
    scale: '180 states',
    difficulty: '研究级',
    tags: ['公共品', '气候治理', '惩罚制度'],
    summary: '把减排看作公共品出资，考察惩罚制度与收益放大能否维持全球合作而非崩塌。',
    mechanism: '合作出资进入公共池放大均分，个体按收益差模仿邻居策略，惩罚改变收益结构。',
    metrics: ['cooperation_rate', 'mean_payoff'],
    experiments: ['惩罚强度扫描', '收益放大对比', '制度冲击反事实'],
    defaults: { steps: 240, params: { multiplier: 1.6, punishment_threshold: 0.3 } },
  },
  {
    id: 'protest-riot-threshold',
    name: '抗议与骚乱阈值',
    subtitle: 'Granovetter 阈值下的动员临界',
    category: '阈值与集体行动',
    domain: '社会运动',
    template: 'social_influence',
    canvas: '社会网络',
    scale: '1k participants',
    difficulty: '进阶',
    tags: ['Granovetter', '临界规模', '复杂传染'],
    summary: '经典骚乱阈值模型：异质阈值分布下，初始激活规模决定动员熄灭还是全面爆发。',
    mechanism: '个体在活跃邻居比例超过自身阈值时参与，阈值方差决定级联是否失控。',
    metrics: ['active', 'activation_rate', 'cascade_size'],
    experiments: ['阈值方差扫描', '初始激活规模', '网络稠密度对比'],
    defaults: { steps: 90, params: { threshold_mean: 0.28 } },
  },
  {
    id: 'bank-run-panic',
    name: '银行挤兑恐慌传导',
    subtitle: '信心阈值与提现级联',
    category: '阈值与集体行动',
    domain: '金融稳定',
    template: 'social_influence',
    canvas: '社会网络',
    scale: '800 depositors',
    difficulty: '研究级',
    tags: ['挤兑', '信心', '级联'],
    summary: '把提现决策建成阈值激活：一旦邻居提现比例过高，恐慌沿储户网络级联传导。',
    mechanism: '储户在观察到的提现比例超过信心阈值时提现，行为通过社交网络自我强化。',
    metrics: ['active', 'activation_rate'],
    experiments: ['信心阈值扫描', '关键储户干预', '注资时点反事实'],
    defaults: { steps: 80, params: { threshold_mean: 0.22 } },
  },
]

export const ABM_RESEARCH_AGENTS: AbmResearchAgent[] = [
  {
    id: 'clarifier',
    name: '建模需求澄清智能体',
    role: '把粗糙选题拆成研究问题、主体、空间、机制、指标和实验约束。',
    when: '用户只给出主题或方向时先启动。',
    checks: ['研究对象是否明确', '空间/网络表示是否明确', '指标是否可观测'],
  },
  {
    id: 'modeler',
    name: '机制建模智能体',
    role: '生成机制多样的候选仿真，并给出 ODD 草稿和可运行模型。',
    when: '澄清完成后生成 5-10 个候选 Simulation。',
    checks: ['机制是否互异', '参数是否可解释', '画布表现是否贴近现象'],
  },
  {
    id: 'validator',
    name: '模型验证智能体',
    role: '采纳或编辑模型后检查结构完整性、参数范围、观测指标和初始化一致性。',
    when: '每次采纳方案、结构编辑或运行失败后启动。',
    checks: ['缺失字段', '无观测指标', '规模异常', 'ODD 与模型不同步'],
  },
  {
    id: 'experimenter',
    name: '实验设计智能体',
    role: '把研究问题转成敏感性、干预、反事实、鲁棒性和理论探索实验。',
    when: '用户要求“比较、扫描、验证、反事实”时启动。',
    checks: ['实验变量是否真实存在', '重复次数是否足够', '图表是否对应指标'],
  },
  {
    id: 'explainer',
    name: 'Trace 解释智能体',
    role: '用运行证据、机制触发和曲线区间解释宏观结果。',
    when: '用户框选曲线、点击智能体、询问异常 tick 时启动。',
    checks: ['引用具体 tick', '引用真实指标', '标注推测与证据边界'],
  },
  {
    id: 'odd-writer',
    name: 'ODD 审校智能体',
    role: '把模型结构整理为 Purpose、Entities、Process、Design Concepts、Initialization、Input、Submodels。',
    when: '模型版本更新、准备导出论文材料时启动。',
    checks: ['七部分齐全', '术语和机制一致', '手写段落保留'],
  },
]

export const ABM_RESEARCH_SKILLS: AbmResearchSkill[] = [
  {
    id: 'scientific-lit-review',
    name: '科研文献综述',
    field: '研究设计',
    summary: '从主题、关键词和经典论文出发生成可追溯的文献地图、争议点和机制候选。来源参考 GitHub 高星 scientific-agent-skills。',
    source: 'K-Dense-AI/scientific-agent-skills',
    sourceUrl: 'https://github.com/K-Dense-AI/scientific-agent-skills',
  },
  {
    id: 'scientific-data-viz',
    name: '科研绘图风格',
    field: '可视化',
    summary: '面向论文图、探索图和对比实验图，约束标题、轴、图例、区间和证据注释的一致性。',
    source: 'K-Dense-AI/scientific-agent-skills',
    sourceUrl: 'https://github.com/K-Dense-AI/scientific-agent-skills',
  },
  {
    id: 'computational-reproducibility',
    name: '计算复现审查',
    field: '复现性',
    summary: '检查随机种子、参数范围、实验重复、数据来源和运行记录，避免结果只停留在单次演示。',
    source: 'K-Dense-AI/scientific-agent-skills',
    sourceUrl: 'https://github.com/K-Dense-AI/scientific-agent-skills',
  },
  {
    id: 'odd-protocol',
    name: 'ODD 协议写作',
    field: '模型文档',
    summary: '把模型配置转为可发表的七部分 ODD 描述，并标出待复核段落。',
  },
  {
    id: 'network-science',
    name: '社会网络建模',
    field: '结构表示',
    summary: '选择 ER、小世界、无标度或经验网络，并解释结构假设对机制的影响。',
  },
  {
    id: 'spatial-abm',
    name: '空间斑块建模',
    field: '空间表示',
    summary: '设计斑块状态、邻域、扩散边界和空间异质性，支持实时状态画布。',
  },
  {
    id: 'sensitivity',
    name: '敏感性分析',
    field: '实验方法',
    summary: '生成单因素、全局、区间不确定性和多种子合奏实验方案。',
  },
  {
    id: 'counterfactual',
    name: '反事实干预',
    field: '因果解释',
    summary: '组织政策时点、分层干预和机制开关，对比可复现运行证据。',
  },
  {
    id: 'trace-explain',
    name: 'Trace 证据解释',
    field: '解释性',
    summary: '从 tick、机制触发、智能体状态和曲线区间中生成有证据边界的解释。',
  },
  {
    id: 'result-plotting',
    name: '结果绘图与证据可视化',
    field: '可视化',
    summary: '生成多变量结果图、区间选择、图卡拖拽缩放、发表级图例和证据解释入口。',
  },
]

export const ABM_RESEARCH_MCP_SERVERS: AbmResearchMcpServer[] = [
  {
    id: 'paper-search-mcp',
    name: '论文检索 MCP',
    category: '科研文献',
    summary: '跨论文源搜索并优先获取开放全文，用于 ABM 案例调研、机制综述和参考文献线索。',
    sourceUrl: 'https://github.com/openags/paper-search-mcp',
  },
  {
    id: 'sequential-thinking',
    name: 'Sequential Thinking MCP',
    category: '科研推理',
    summary: '把建模假设、实验分支、修订和验证步骤结构化，适合复杂研究任务的多轮规划。',
    sourceUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
  },
  {
    id: 'filesystem',
    name: 'Filesystem MCP',
    category: '项目资料',
    summary: '让研究会话读取和组织本地论文、数据、运行记录与导出材料，并保留可审计的路径边界。',
    sourceUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
  },
  {
    id: 'git',
    name: 'Git MCP',
    category: '版本追踪',
    summary: '把模型、ODD、实验配置和论文材料的变更纳入版本证据，便于复现实验与团队协作。',
    sourceUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git',
  },
]
